#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

echo "==> Updating..."
script/update

echo "==> Starting MSSQL database Docker container"
docker-compose up -d && script/setup-data

echo "==> Starting the development server..."
npm start
